"""
This file contains settings to model and training process

"""
########## PATH SETTINGS #######################
input_source_dir_folder = '/ai-data/utf_encoded_data'
output_filtered_dir_folder = '/home/ppirog/projects/cars-regression/filtered_dataset'
output_filtered_file_name = 'filtered_file.csv'

#####  PANDAS SETTINGS #########################
sep = ';'
encoding = 'utf-8'
log10_target = True

###### FEATURES AND TARGET #####################
# Target value to predict
TARGET = ['Amount']

# Column names with categorical values
FEATURES_CATEGORICAL = ['IC_slug',
                        'Package',
                        'Body',
                        'Brand',
                        'Fuel_type',
                        'Gearbox_type',
                        'Generation_type',
                        'Import_status',
                        'LPG_system',
                        'Model_type',
                        'Ownership_mode',
                        'Steering_wheel_side',
                        'Subject_type',
                        'Voivodeship',
                        'Marital_status',
                        'Version_type_name',
                        'AC_PREVIOUS_INSURANCE_COMPANY_PREVIOUS_YEAR',
                        'TPL_PREVIOUS_INSURANCE_COMPANY_PREVIOUS_YEAR',
                        'Commune',
                        'County',
                        'Customer_Contact_ZIP',
                        'Place',
                        'Parking_zip_code']

# Column names with numeric values
FEATURES_NUMERICAL = ['Capacity_ccm',
                      'Doors',
                      'Gears',
                      'Key_pairs',
                      'Mileage',
                      'Power_kW',
                      'Younges_driver_age',
                      'AC_CLAIMS_COUNT__1_YEAR',
                      'AC_CLAIMS_COUNT__10_YEAR',
                      'AC_CLAIMS_COUNT__11_YEAR',
                      'AC_CLAIMS_COUNT__12_YEAR',
                      'AC_CLAIMS_COUNT__13_YEAR',
                      'AC_CLAIMS_COUNT__14_YEAR',
                      'AC_CLAIMS_COUNT__15_YEAR',
                      'AC_CLAIMS_COUNT__2_YEAR',
                      'AC_CLAIMS_COUNT__3_YEAR',
                      'AC_CLAIMS_COUNT__4_YEAR',
                      'AC_CLAIMS_COUNT__5_YEAR',
                      'AC_CLAIMS_COUNT__6_YEAR',
                      'AC_CLAIMS_COUNT__7_YEAR',
                      'AC_CLAIMS_COUNT__8_YEAR',
                      'AC_CLAIMS_COUNT__9_YEAR',
                      'AC_CLAIMS_COUNT_PREVIOUS_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__1_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__10_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__11_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__12_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__13_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__14_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__15_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__2_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__3_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__4_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__5_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__6_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__7_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__8_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__9_YEAR',
                      'AC_CLAIMS_WITHOUT_REFUSAL_COUNT_PREVIOUS_YEAR',
                      'AC_EVENTS_COUNT__1_YEAR',
                      'AC_EVENTS_COUNT__10_YEAR',
                      'AC_EVENTS_COUNT__11_YEAR',
                      'AC_EVENTS_COUNT__12_YEAR',
                      'AC_EVENTS_COUNT__13_YEAR',
                      'AC_EVENTS_COUNT__14_YEAR',
                      'AC_EVENTS_COUNT__15_YEAR',
                      'AC_EVENTS_COUNT__2_YEAR',
                      'AC_EVENTS_COUNT__3_YEAR',
                      'AC_EVENTS_COUNT__4_YEAR',
                      'AC_EVENTS_COUNT__5_YEAR',
                      'AC_EVENTS_COUNT__6_YEAR',
                      'AC_EVENTS_COUNT__7_YEAR',
                      'AC_EVENTS_COUNT__8_YEAR',
                      'AC_EVENTS_COUNT__9_YEAR',
                      'AC_EVENTS_COUNT_PREVIOUS_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__1_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__10_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__11_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__12_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__13_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__14_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__15_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__2_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__3_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__4_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__5_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__6_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__7_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__8_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT__9_YEAR',
                      'AC_EVENTS_WHERE_CULPRIT_COUNT_PREVIOUS_YEAR',
                      'AC_INSURANCE_COMPANIES_COUNT__10_YEAR',
                      'AC_INSURANCE_COMPANIES_COUNT__15_YEAR',
                      'AC_INSURANCE_COMPANIES_COUNT__5_YEAR',
                      'AC_INSURANCE_PERIOD__5_YEAR',
                      'AC_POLICY_COUNT__7_YEAR',
                      'TPL_CLAIMS_COUNT__1_YEAR',
                      'TPL_CLAIMS_COUNT__10_YEAR',
                      'TPL_CLAIMS_COUNT__11_YEAR',
                      'TPL_CLAIMS_COUNT__12_YEAR',
                      'TPL_CLAIMS_COUNT__13_YEAR',
                      'TPL_CLAIMS_COUNT__14_YEAR',
                      'TPL_CLAIMS_COUNT__15_YEAR',
                      'TPL_CLAIMS_COUNT__2_YEAR',
                      'TPL_CLAIMS_COUNT__3_YEAR',
                      'TPL_CLAIMS_COUNT__4_YEAR',
                      'TPL_CLAIMS_COUNT__5_YEAR',
                      'TPL_CLAIMS_COUNT__6_YEAR',
                      'TPL_CLAIMS_COUNT__7_YEAR',
                      'TPL_CLAIMS_COUNT__8_YEAR',
                      'TPL_CLAIMS_COUNT__9_YEAR',
                      'TPL_CLAIMS_COUNT_PREVIOUS_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__1_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__10_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__11_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__12_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__13_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__14_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__15_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__2_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__3_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__4_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__5_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__6_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__7_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__8_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__9_YEAR',
                      'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT_PREVIOUS_YEAR',
                      'TPL_EVENTS_COUNT__1_YEAR',
                      'TPL_EVENTS_COUNT__10_YEAR',
                      'TPL_EVENTS_COUNT__11_YEAR',
                      'TPL_EVENTS_COUNT__12_YEAR',
                      'TPL_EVENTS_COUNT__13_YEAR',
                      'TPL_EVENTS_COUNT__14_YEAR',
                      'TPL_EVENTS_COUNT__15_YEAR',
                      'TPL_EVENTS_COUNT__2_YEAR',
                      'TPL_EVENTS_COUNT__3_YEAR',
                      'TPL_EVENTS_COUNT__4_YEAR',
                      'TPL_EVENTS_COUNT__5_YEAR',
                      'TPL_EVENTS_COUNT__6_YEAR',
                      'TPL_EVENTS_COUNT__7_YEAR',
                      'TPL_EVENTS_COUNT__8_YEAR',
                      'TPL_EVENTS_COUNT__9_YEAR',
                      'TPL_EVENTS_COUNT_PREVIOUS_YEAR',
                      'TPL_INSURANCE_COMPANIES_COUNT__10_YEAR',
                      'TPL_INSURANCE_COMPANIES_COUNT__15_YEAR',
                      'TPL_INSURANCE_COMPANIES_COUNT__5_YEAR',
                      'TPL_INSURANCE_PERIOD__5_YEAR',
                      'TPL_POLICY_COUNT__7_YEAR',
                      'Estimated_Vehicle_value',
                      'Maximum_mass',
                      'Load_capacity',
                      'Insured_days']

# All features
FEATURES = FEATURES_CATEGORICAL + FEATURES_NUMERICAL
# This integer value features are converted to categories
FEATURES_INT_TO_OBJ = ['Gears', 'Doors', 'Key_pairs']
# This feature values have spaces, spaces are replaced
FEATURES_TO_REMOVE_SPACE_FROM_CATEGORIES = ['Generation_type', 'Version_type_name', 'Commune']

# PREPROCESSING SETTINGS
# split histogram into N bins
number_of_bins_for_numeric_features = 5
# drop feature if 98 % of values are identical
drop_constant_threshold = 0.98
